#!/bin/bash
set -e

# DJGPP cross-compiler build script for DUCKHUNT (Quack Hunt)
# Target: Pentium D (Prescott core) - uses SSE/SSE2/SSE3
#
# Uses CWSDPR0.EXE (ring-0 DPMI server) so the program has full access
# to CR4.OSFXSR (SSE enable) — without ring 0, SSE instructions crash.
DJGPP_ROOT="${DJGPP_ROOT:-/opt/djgpp}"

export PATH="$DJGPP_ROOT/bin:$DJGPP_ROOT/i586-pc-msdosdjgpp/bin:$PATH"
export GCC_EXEC_PREFIX="$DJGPP_ROOT/lib/gcc/"
export DJDIR="$DJGPP_ROOT/i586-pc-msdosdjgpp"

CC=i586-pc-msdosdjgpp-gcc
STRIP=i586-pc-msdosdjgpp-strip
STUBEDIT="$DJGPP_ROOT/i586-pc-msdosdjgpp/bin/stubedit"

# Common flags
COMMON="-O3 -ffast-math -funroll-loops -fomit-frame-pointer -Wall -Wno-unused-function"

if [ "$1" = "dosbox" ]; then
    # DOSBox-X safe: x87 FPU only, no SSE (DOSBox-X DPMI runs ring 3,
    # can't set CR4.OSFXSR → any SSE instruction = GPF).
    # Still benefits from GCC 12's superior optimization vs Watcom.
    CFLAGS="-march=pentium-mmx -mtune=prescott -mno-sse -mfpmath=387 $COMMON"
    echo "Building DUCKHUNT (DJGPP/GCC - DOSBox-X safe, x87 only)..."
else
    # Full Pentium D: SSE2/SSE3, all float/double via SSE
    # Ring 0 via CWSDPR0 for CR4.OSFXSR (SSE enable)
    CFLAGS="-march=prescott -mfpmath=sse $COMMON"
    echo "Building DUCKHUNT (DJGPP/GCC - Pentium D, full SSE2/SSE3)..."
fi

echo "  CC: $($CC --version | head -1)"
echo "  CFLAGS: $CFLAGS"

$CC $CFLAGS -o duckgcc.exe DUCKHUNT.C -lm

# Patch the stub to load CWSDPR0 (ring-0 DPMI server) instead of CWSDPMI.
# Required: CWSDPMI runs at ring 3, so CR4.OSFXSR can't be set, causing
# a seg violation on the first SSE instruction generated by -mfpmath=sse.
echo "Patching DPMI server to CWSDPR0 (ring 0)..."
$STUBEDIT duckgcc.exe dpmi=cwsdpr0.exe

echo "Stripping..."
$STRIP duckgcc.exe
mv duckgcc.exe DUCKGCC.EXE

ls -la DUCKGCC.EXE
echo "Done: DUCKGCC.EXE"

# ---- 16bpp highcolor version ----
echo ""
if [ "$1" = "dosbox" ]; then
    echo "Building DUCK16 highcolor (DJGPP/GCC - DOSBox-X safe, x87 only)..."
else
    echo "Building DUCK16 highcolor (DJGPP/GCC - Pentium D, full SSE2/SSE3)..."
fi

$CC $CFLAGS -o duck16gcc.exe DUCKHUNTHC.C -lm
$STUBEDIT duck16gcc.exe dpmi=cwsdpr0.exe
$STRIP duck16gcc.exe
mv duck16gcc.exe DUCK16GCC.EXE

ls -la DUCK16GCC.EXE
echo "Done: DUCK16GCC.EXE"
echo ""
echo "Requires CWSDPR0.EXE in the same directory or PATH."
echo ""
echo "Usage: $0          # Full Pentium D SSE2/SSE3 (real hardware only)"
echo "       $0 dosbox   # DOSBox-X safe (x87 only, works in any DOSBox)"
