# PLASMA - 8bpp VESA Plasma Demo with VSync
# OpenWatcom 2.0 wmake build file

CC      = wcc386
LINK    = wlink
CFLAGS  = -bt=dos -3r -ox -s -zq
TARGET  = PLASMA

OBJS    = $(TARGET).obj VGA.obj WAVE.obj

all: $(TARGET).exe

$(TARGET).obj: $(TARGET).C VGA.H WAVE.H
	$(CC) $(CFLAGS) $[@

VGA.obj: VGA.C VGA.H
	$(CC) $(CFLAGS) $[@

WAVE.obj: WAVE.C WAVE.H
	$(CC) $(CFLAGS) $[@

$(TARGET).exe: $(OBJS)
	$(LINK) system dos4g name $(TARGET) file $(TARGET),VGA,WAVE option quiet

clean: .SYMBOLIC
	del $(TARGET).obj
	del VGA.obj
	del WAVE.obj
	del $(TARGET).exe
