# PLASMA + WATERDRP - 8bpp VESA Demos
# OpenWatcom 2.0 wmake build file

CC      = wcc386
LINK    = wlink
CFLAGS  = -bt=dos -3r -ox -s -zq

all: PLASMA.exe WATERDRP.exe

# --- PLASMA ---

PLASMA.obj: PLASMA.C VGA.H WAVE.H
	$(CC) $(CFLAGS) $[@

VGA.obj: VGA.C VGA.H
	$(CC) $(CFLAGS) $[@

WAVE.obj: WAVE.C WAVE.H
	$(CC) $(CFLAGS) $[@

PLASMA.exe: PLASMA.obj VGA.obj WAVE.obj
	$(LINK) system dos4g name PLASMA file PLASMA,VGA,WAVE option quiet

# --- WATERDRP ---

WATERDRP.obj: WATERDRP.C VGA.H
	$(CC) $(CFLAGS) $[@

WATERDRP.exe: WATERDRP.obj VGA.obj
	$(LINK) system dos4g name WATERDRP file WATERDRP,VGA option quiet

clean: .SYMBOLIC
	del *.obj
	del PLASMA.exe
	del WATERDRP.exe
